version: '3.4'


services:
  rabbitmq:
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"
      - "15672:15672"

  ms-sql-1:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55W0rd"
    ports:
      -  "1463:1433"

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    environment:
      DefaultHost: "ms-sql-1"
      RabbitMQ: "rabbitmq"
    ports:
     - "8081:80" 
    depends_on:
     - ms-sql-1
     - rabbitmq

  basket.api:
     image: ${DOCKER_REGISTRY-}basketapi
     build: 
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
     ports:
      - "8082:80" 
     environment:
       CatalogAPI: "http://catalog.api:80/"
       RabbitMQ: "rabbitmq"
       ASPNETCORE_ENVIRONMENT: Development
     depends_on:
       - rabbitmq
       - catalog.api